version: '3.8'

services:
  # Nasza aplikacja webowa
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - redis

  # Kontener bazy danych Redis
  redis:
    image: "redis:alpine"